#### PyTorch Basic Tensor Manipulation 
1. Vector, Matrix, and Tensor
    - 2D Tensor(Typical Simple Setting) 
        - |t| = batch size , dim
    - 3D Tensor(Typical Computer Vision) 
        - |t| = batch size, width, height
    - 3D Tensor(Typical Natural Language Processing) 
        - |t| = batch size, length, dim 
     
    
2. NumPy Review 
3. PyTorch Tensor Allocation 
4. Matrix Multiplication 
5. Other Basic Ops 



In [ ]:
import numpy as np
import torch
import sys 

In [ ]:
def show_version():
    print("========version========")
    print(f"python : {sys.version}")
    print(f"numpy : {np.__version__}")
    print(f"torch : {torch.__version__}")


In [ ]:
show_version()

========version========
python : 3.7.13 (default, Apr 24 2022, 01:04:09) 
[GCC 7.5.0]
numpy : 1.21.6
torch : 1.12.0+cu113


#### 1D Array with Numpy

In [ ]:
t = np.array([0. , 1. , 2.,  3., 4., 5., 6.])
print(f"Type : {type(t)}")
print(f"Shape :  {t.shape}")
print(f"Length : {len(t)}")
print(f"Rank : {t.ndim}")
print(f"{t}")

Type : <class 'numpy.ndarray'>
Shape :  (7,)
Length : 7
Rank : 1
[0. 1. 2. 3. 4. 5. 6.]


In [ ]:
print(f"t[0] t[1] , t[-1] = {t[0], t[1], t[-1]}")
print(f"t[2:5] = {t[2:5]}")
print(f"t[4:-1] = {t[4:-1]}")
print(f"t[:2] = {t[:2]}")
print(f"t[3:] = {t[3:]}")

t[0] t[1] , t[-1] = (0.0, 1.0, 6.0)
t[2:5] = [2. 3. 4.]
t[4:-1] = [4. 5.]
t[:2] = [0. 1.]
t[3:] = [3. 4. 5. 6.]


#### 2D Array with Numpy

In [ ]:
t = np.array([[1., 2., 3., ], 
              [4., 5., 6.], 
              [7., 8., 9.],
              [10., 11., 12.]])

print(f"Type : {type(t)}")
print(f"Shape :  {t.shape}")
print(f"Length : {len(t)}")
print(f"Rank : {t.ndim}")
print(f"{t}")

Type : <class 'numpy.ndarray'>
Shape :  (4, 3)
Length : 4
Rank : 2
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


#### 1D Array width PyTorch 

In [ ]:
t = torch.FloatTensor([0, 1, 2, 3, 4, 5, 6])
print(f"Type : {type(t)}")
print(f"Shape :  {t.shape}")
print(f"Length : {len(t)}")
print(f"Rank : {t.ndim}")
print(f"Size  : {t.size()}")
print(f"{t}")

Type : <class 'torch.Tensor'>
Shape :  torch.Size([7])
Length : 7
Rank : 1
Size  : torch.Size([7])
tensor([0., 1., 2., 3., 4., 5., 6.])


In [ ]:
print(f"t[2:5] = {t[2:5]}")
print(f"t[4:-1] = {t[4:-1]}")
print(f"t[:2] = {t[:2]}")
print(f"t[3:] = {t[3:]}")

t[2:5] = tensor([2., 3., 4.])
t[4:-1] = tensor([4., 5.])
t[:2] = tensor([0., 1.])
t[3:] = tensor([3., 4., 5., 6.])


#### 2D Array with PyTorch 

In [ ]:
t = torch.FloatTensor([[1., 2., 3., ], 
                       [4., 5., 6.], 
                       [7., 8., 9.],
                       [10., 11., 12.]])

print(f"Type : {type(t)}")
print(f"Shape :  {t.shape}")
print(f"Length : {len(t)}")
print(f"Rank : {t.ndim}")
print(f"Szie : {t.size()}")
print(f"{t}")

Type : <class 'torch.Tensor'>
Shape :  torch.Size([4, 3])
Length : 4
Rank : 2
Szie : torch.Size([4, 3])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
print(f"t[:, 1] = {t[:, 1]}")
print(f"t[:. 1].size() {t[:, 1].size()}")
print(f"t[:, :-1]{t[:, :-1]}")

t[:, 1] = tensor([ 2.,  5.,  8., 11.])
t[:. 1].size() torch.Size([4])
t[:, :-1]tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


#### Broadcasting

In [ ]:
#Same shape 
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[3, 3]])
print(m1 + m2)

tensor([[6., 6.]])


In [ ]:
#Vector + scale 
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3]])
print(m1 + m2)

tensor([[4., 5.]])


In [ ]:
#2 * 1 vertor + 1 * 2 vector 
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


#### Multiplication vs Matrix Multiplication 



In [ ]:
print()
print("============")
print("Multiplication vs Matrix Multiplication")
print("============")
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

print(f"Shape of Matrix 1 : {m1.shape}")
print(f"Shape of Matrix 2 : {m2.shape}")
print(m1.matmul(m2))

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print(m1 * m2)
print(m1.mul(m2))


Multiplication vs Matrix Multiplication
Shape of Matrix 1 : torch.Size([2, 2])
Shape of Matrix 2 : torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


#### Mean 

In [ ]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [ ]:
t = torch.LongTensor([1.0, 2.0])
try : 
    print(t.mean())
except Exception as exc :
    print(exc) 

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))


tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


#### Sum

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


#### Max

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.max(dim=0)[0])
print(t.max(dim=1)[1])


tensor([[1., 2.],
        [3., 4.]])
tensor([3., 4.])
tensor([1, 1])
