In [1]:
import torch 
import numpy as np 
import sys 

#### View 

In [11]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]], 
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(f"shape of t : {t.shape}")
print(f"dimension of t : {t.ndim}")
print(f"size of t : {t.size}")
print(f"length of t {len(t)}")
print(f"type of t : {type(t)}")

shape of t : (2, 2, 3)
dimension of t : 3
size of t : 12
length of t 2
type of t : <class 'numpy.ndarray'>


In [14]:

print(f"shape of ft : {ft.shape}")
print(f"dimension of ft : {ft.ndim}")
print(f"size of ft : {ft.size()}")
print(f"length of ft {len(ft)}")
print(f"type of ft : {type(ft)}")

shape of ft : torch.Size([2, 2, 3])
dimension of ft : 3
size of ft : torch.Size([2, 2, 3])
length of ft 2
type of ft : <class 'torch.Tensor'>


In [17]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [19]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


#### Squeeze 

In [21]:
ft = torch.FloatTensor([[0], [1], [2]])
print(f"shape of ft : {ft.shape}")
print(f"dimension of ft : {ft.ndim}")
print(f"size of ft : {ft.size()}")
print(f"length of ft {len(ft)}")
print(f"type of ft : {type(ft)}")

shape of ft : torch.Size([3, 1])
dimension of ft : 2
size of ft : torch.Size([3, 1])
length of ft 3
type of ft : <class 'torch.Tensor'>


In [22]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


#### Unsqueeze 

In [23]:
ft = torch.FloatTensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [24]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [25]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [26]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [27]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


#### Type Casting 

In [29]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt.shape)
print(lt)

torch.Size([4])
tensor([1, 2, 3, 4])


In [30]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [31]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [32]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


#### Concatenate 

In [36]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))


tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


#### Stacking 

In [39]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [41]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


#### Ones and Zeros 

In [42]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [44]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### In-Place Operation 

In [46]:
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
