#### Logistic Regression 
- Reminder 
    - Hypothesis 
$$ H(X) = \frac{1}{1+e^{-W^T X}}$$
    - COST 
$$ cost(W) = -\frac{1}{m} \sum y \log\left(H(x)\right) + (1-y) \left( \log(1-H(x) \right) $$
        - If $y \simeq H(x)$, cost is near 0.
        - If $y \neq H(x)$, cost is high.
    - Weight Updata via Gradient Descent 
$$W : = W - \alpha\frac{\partial}{\partial W} cost(W) $$
- Computing Hypothesis 
- Computing Cost Function 
$$ cost(W) = -\frac{1}{m} \sum y \log\left(H(x)\right) + (1-y) \left( \log(1-H(x) \right) $$
- Evalution 
- Higher Implementation 


In [1]:
import numpy as np 
import pandas as pd 
import torch 
import torch.nn.functional as F 
import torch.nn as nn 
import torch.optim as optim 

In [ ]:
torch.manual_seed(1)

In [2]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]

In [3]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)
print(x_train.shape)
print(y_train.shape)

torch.Size([6, 2])
torch.Size([6, 1])


In [6]:
print(f"e^1 equals : {torch.exp(torch.FloatTensor([1]))}")

e^1 equals : tensor([2.7183])


In [9]:
W = torch.zeros((2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(W)+b)))
print(hypothesis)
print(hypothesis.shape)
print('1/(1+e^{-1}) equals: ', torch.sigmoid(torch.FloatTensor([1])))

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)
torch.Size([6, 1])
1/(1+e^{-1}) equals:  tensor([0.7311])


In [11]:
hypothesis = torch.sigmoid(x_train.matmul(W) + b)
print(hypothesis)
print(hypothesis.shape)
print(y_train)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward0>)
torch.Size([6, 1])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


In [13]:
losses  =-(y_train[0] * torch.log(hypothesis[0]) + (1 - y_train[0]) * torch.log(1 - hypothesis[0]))
print(losses)


tensor([0.6931], grad_fn=<NegBackward0>)


In [14]:
losses = -(y_train * torch.log(hypothesis) +  (1 - y_train) * torch.log(1 - hypothesis))
print(losses)

tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931]], grad_fn=<NegBackward0>)


In [15]:
cost = losses.mean()
print(cost)

tensor(0.6931, grad_fn=<MeanBackward0>)


In [16]:
F.binary_cross_entropy(hypothesis, y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward0>)